num_samples: 120000
devices:
  - name: "64 v0.9"       # Serial Number of the Device
    calibration: [1,1,1]  # No calibration
    speed: 1000           # in Hz
  - name: "95 v1.0"       # Serial Number of the Device
    calibration: [1,1,1]  # No calibration
    speed: 1000           # in Hz. Aquisition Frequency of OptoForce Sensor Data
  
