num_samples: 120000
devices:
  - name: "64 v0.9"       # Device Name
    calibration: [1,1,1]  # No calibration
    speed: 1000           # in Hz
    SN: "IRE004"          # Serial Number of the Device
  - name: "64 v0.9"       # Device Name
    calibration: [1,1,1]  # No calibration
    speed: 1000           # in Hz. Aquisition Frequency of OptoForce Sensor Data
    SN: "IRE005"          # Serial Number of the Device
  
